export const authTypes = {
    AUTH_START: 'AUTH_STARTING',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',

    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    
    PROFILE_START: 'PROFILE_START',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAIL: 'PROFILE_FAIL',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',

   
};

export const productsTypes = {
    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',

    GET_PRODUCT_START: 'GET_PRODUCT_START',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',

    GET_PRODUCT_BY_ID_START: 'GET_PRODUCT_BY_ID_START',
    GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
    GET_PRODUCT_BY_ID_FAIL: 'GET_PRODUCT_BY_ID_FAIL',

    GET_PRODUCT_BY_START: 'GET_PRODUCT_BY_START',
    GET_PRODUCT_BY_SUCCESS: 'GET_PRODUCT_BY_SUCCESS',
    GET_PRODUCT_BY_FAIL: 'GET_PRODUCT_BY_FAIL',

    UPDATE_PRODUCT_START: ' UPDATE_PRODUCT_START',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAIL: 'UPDATE_PRODUCT_FAIL',

    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL'
};

export const adminTypes = {
    ADD_ADMIN_START: 'ADD_ADMIN_START',
    ADD_ADMIN_SUCCESS: 'ADD_ADMIN_SUCCESS',
    ADD_ADMIN_FAIL: 'ADD_ADMIN_FAIL',

    GET_USERS_START: "GET_USERS_START",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAIL: "GET_USERS_FAIL",

};

export const userTypes = {
    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILE: 'DELETE_USER_FAIL',

    UPDATE_USER_START: 'UPDATE_USER_START',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

    ADD_TO_CART_START: 'ADD_TO_CART_START',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL',

    REMOVE_FROM_CART_START: 'REMOVE_FROM_CART_START',
    REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
    REMOVE_FROM_CART_FAIL: 'REMOVE_FROM_CART_FAIL',

    GET_USER_BY_START: 'GET_USER_BY_START',
    GET_USER_BY_SUCCESS: 'GET_USER_BY_SUCCESS',
    GET_USER_BY_FAIL: 'GET_USER_BY_FAIL',

    GET_CART_START: 'GET_CART_START',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    GET_CART_FAIL: 'GET_CART_FAIL',
    

    UPDATE_CART_START: 'UPDATE_CART_START',
    UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
    UPDATE_CART_FAIL: 'UPDATE_CART_FAIL',
}